ILS / LOC Fixes
InfiniteFlightAirportEditing/Navigation pull request #2241
Opened 2021-04-08 17:36 UTC by zhf21

2021-04-08 17:52 UTC, zhf21 commented
Heading out for a bit; will resume around 7pm.

2021-04-09 01:45 UTC, zhf21 commented
All good to go! I guess Travis didn't like the double 0s for the bearing.

2021-04-09 05:58 UTC, velocity23 requested changes

2021-04-09 05:58 UTC, velocity23 commented on Glideslope.json
> +   "glideslope": 3.000047,
This is a confusing one, but this should be 3.0000047 because the bearing is technically 000.47

2021-04-09 13:47 UTC, velocity23 approved these changes

2021-04-09 13:47 UTC, merged