ILS / LOC Fixes
InfiniteFlightAirportEditing/Navigation pull request #2309
Opened 2021-04-13 22:08 UTC by SuhasIF

OEAB - (Fixed #2306)

2021-04-27 15:44 UTC, SuhasIF commented
I'd like this to be merged, please. Thanks!

2021-04-27 20:48 UTC, velocity23 requested changes

2021-04-27 20:48 UTC, velocity23 commented on Glideslope.json
> +   "glideslope": 3.00028519,
Should be 3.0028519 (heading is 285.19 not 28.519)

2021-05-09 12:12 UTC, velocity23 commented
@SuhasIF are you planning to fix this?

2021-05-10 20:36 UTC, SuhasIF commented
@velocity23 fixed. Apologies for the delay!

2021-05-10 21:05 UTC, merged