ILS/LOC Changes
InfiniteFlightAirportEditing/Navigation pull request #2387
Opened 2021-05-25 21:11 UTC by GBKarp

2021-05-27 14:22 UTC, GBKarp commented
5 airports, it's ready to merge!

2021-05-30 23:34 UTC, velocity23 requested changes

2021-05-30 23:34 UTC, velocity23 commented on Glideslope.json
> +   "glideslope": 3.00017483,
Should be 3.0017483

2021-05-30 23:56 UTC, velocity23 approved these changes

2021-05-30 23:56 UTC, merged